### ISSUE TITLE
Copy and move data on device between the arrays on GPU

### ISSUE THREAD

**Issue by Kerkil** [viennacl/viennacl-dev#114]
I am writing a program that uses linear algebra and signal processing for GPU/CPU. I need to copy/move the data on device (GPU) created by another OpenCL library (e.g., ArrayFire: https://github.com/arrayfire/arrayfire) to a viennacl::matrix in ViennaCL without going through the host not to incur additional cost for data transfer. How can I copy or move (preferably using a pointer to an array on device) the data between the two arrays on device created by ViennaCL and other libraries?

Maybe it's possible to get and set a pointer to a datatype in ViennaCL?

**Comment by karlrupp** [comment]
Hi,

you can 'implant' an existing OpenCL buffer into a matrix using the respective constructors:
https://github.com/viennacl/viennacl-dev/blob/master/viennacl/matrix.hpp#L709

However, you will most likely also use your own (or ArrayFire's) OpenCL context with devices and command queues. They can be made known to ViennaCL by following the last couple of lines of this example: https://github.com/viennacl/viennacl-dev/blob/master/examples/tutorial/custom-context.cpp

Best regards,
Karli

**Comment by Kerkil** [comment]
@karlrupp Thanks for the help.
Would the first approach of 'implanting' work too? I have a device pointer that is cast to `cl_mem` type and passed to the constructor in https://github.com/viennacl/viennacl-dev/blob/master/viennacl/matrix.hpp#L709 as 
```
float *dA = A.device<float>(); // ArrayFire device pointer
af::sync() // ArrayFire gives the control to ViennaCL

// Construct a ViennaCL matrix object
viennacl::matrix<ScalarType> B((cl_mem)dA, N, N);
```
However, this does not seem to *move* the contents of A into B. 

I printed the values with
```
std::cout << "B(0,0): " << B(0,0) << std::endl;
```
Is there a command to use to print out the entire matrix `B`? A search in the user manual returned nothing.

Thanks for the help again. 

I am in the process of trying the second approach.

**Comment by karlrupp** [comment]
If you want to copy the data, create another matrix ('C') which you construct from B, e.g.

    viennacl::matrix<ScalarType> B((cl_mem)dA, N, N);
    viennacl::matrix<ScalarType> C(B);

This will then create a new buffer and copy the data over. You can also merge these two lines into one:
        
    viennacl::matrix<ScalarType> C = viennacl::matrix<ScalarType>((cl_mem)dA, N, N);


Printing the whole matrix is possible via

     std::cout << B << std::endl;

Should we state the availability of an overloaded operator<< more explicitly?

**Comment by Kerkil** [comment]
@karlrupp Thanks for the help again. 

1. It would be great to document explicitly the overloaded operator `<<.`

2. Is `C(B)` copying the data into a different (GPU) memory location from the location of memory of 'B'? I'd like to avoid *copying* the data. I'd rather directly grab the pointer and directly access the memory location of `B`. Could you please clarify how 
```
viennacl::matrix<ScalarType> C = viennacl::matrix<ScalarType>((cl_mem)dA, N, N);
``` 
works in that regard? 

Thanks a lot for your help again.

**Comment by Kerkil** [comment]
Sorry. I apologize for the premature concern. It looks like ViennaCL DOES grab the pointer and modify the array IN-PLACE. Awesome. Thanks!

**Comment by karlrupp** [comment]
Hi,

if you don't want to copy, but just wrap the data, then you don't need C and you are fine with just

     viennacl::matrix<ScalarType> B((cl_mem)dA, N, N);

I'm glad it works for you now :-)

Best regards,
Karli
