### ISSUE TITLE
SVD singular value order

### ISSUE THREAD

**Issue by Kerkil** [viennacl/viennacl-dev#117]
I am taking an SVD of a matrix in ViennaCL and verifying the results against Matlab's SVD:
```
viennacl::linalg::svd(A, QL, QR);
```

While I think I am getting the right set of singular vectors, the order of the singular vectors does not match those from Matlab nor the sign of the vectors, assuming the singular values are all nonnegative. 

Are the singular values ordered in a decreasing fashion (max to min)? 

Is there a way to get singular values associated with the singular vectors as well? With the `svd` function that I am using now, I think I only get the two orthonormal bases (left and right singular vectors).

**Comment by Kerkil** [comment]
I bumped into this thread http://sourceforge.net/p/viennacl/discussion/1143678/thread/7c37614f/) on the web related to the current issue. 

I am actually fine using unordered singular value/vector pairs. One concern is though that I often truncate  the singular vector matrix (usually left one) to the row space of the original matrix. 

For this, it would be helpful if I can somehow be ensured that all nonzero singular values are clustered although they don't have a particular order. This will allow me to safely truncate and keep the row space from the results of ViennaCL's SVD. Is this the case? (Namely, do the zero singular values follow the nonzero singular values?)

**Comment by karlrupp** [comment]
The relative order of singular values and singular vectors is fixed, yes. If not, then SVD wouldn't make any sense ;-)

Regardless, as you can see from the referenced thread, there is repeated request for an SVD with ordered singular values, so we will add that once we stabilize SVD (i.e. make it available for backends other than OpenCL).

**Comment by Kerkil** [comment]
Thanks @karlrupp. Sorry for the confusion. My question is whether all the nonzero singular values are clustered together and come before zero singular values. I'd like to make sure that when I truncate the singular vector matrix by the rank of the matrix, all those singular vectors are associated only with nonzero singular values. Hope this clarifies my question a little bit more.

**Comment by Kerkil** [comment]
Testing a few matrix seems to indicate that it is true that the nonzero singular values are clustered.
