### ISSUE TITLE
Synchronization between libraries or kernel calls

### ISSUE THREAD

**Issue by Kerkil** [viennacl/viennacl-dev#118]
I am moving/copying memory back and forth between ArrayFire (another GPU library) and ViennaCL. I'd like to make sure that ViennaCL finishes all its computations before the memory gets accessed by ArrayFire. Is there a "device" like ArrayFire's `af::sync` (http://www.arrayfire.com/docs/group__array__func__cpp__sync.htm) to ensure that multiple GPU libraries share the context and the command queue and do not race?

This question is related to the interoperability between multiple GPU libraries sharing the context and command queue (https://github.com/viennacl/viennacl-dev/issues/114)

**Comment by Kerkil** [comment]
Would `void viennacl::backend::finish()` serve my purpose?

**Comment by PhilippeTillet** [comment]
Yes.
