### ISSUE TITLE
Device memory raw pointer

### ISSUE THREAD

**Issue by Kerkil** [viennacl/viennacl-dev#119]
I need to pass the device pointer to another function to construct an object in another GPU library. Is there a way to get a raw pointer to a ViennaCL object (e.g., `viennacl::matrix<ScalarType> A`)?

**Comment by PhilippeTillet** [comment]
A.context().devices()[0].id() should work. Please read the documentation...!
Also, could you label further similar posts as questions? :p Thanks.

**Comment by Kerkil** [comment]
@PhilippeTillet Thanks for the help. 

Do you mean `A.handle().opencl_handle().context().devices()[0].id()`? I am not seeing `context()` as a member function of `A`. Also, this seems to return the device id pointer rather than the raw pointer to the buffer: 
```
usr/local/include/af/array.h:48:9: note: candidate constructor not viable: cannot convert argument of incomplete type 'cl_device_id' (aka '_cl_device_id *') to 'dim_type' (aka 'int')
        array(dim_type d0, dim_type d1, dim_type d2, dim_type d3, dtype ty = f32);
```
Could you help me a bit more with this?

As a note, I wasn't able to find the related info on the documentation (at least in User guide Ch. 8-10). Are you referring to this PDF (http://viennacl.sourceforge.net/viennacl-manual-current.pdf)? If you refer to another source of documentation, could you please point me to it? What would be the current best source of documentation? Thanks for the help again.

I will make sure label similar posts as questions. Thanks for the heads up.

**Comment by PhilippeTillet** [comment]
You're right about using .handle().opencl_handle().context() instead; sorry!
I am confused, are you looking for opencl's device handle or memory handle? In the latter case, A.handle().opencl_handle().get() should work

**Comment by Kerkil** [comment]
It was the latter. Thanks! I think it successfully returns `cl_mem *` type. Thanks for the help.

P.S. I can't figure out how to add a label. It does not let me add a label to the issue. I am not seeing the checkbox described in this instruction for adding labels to issues (https://help.github.com/articles/applying-labels-to-issues-and-pull-requests/)

**Comment by karlrupp** [comment]
@Kerkil : Latest documentation is here: http://viennacl.sourceforge.net/doc/ and can be found by clicking on "Documentation" at http://viennacl.sourceforge.net/

**Comment by Kerkil** [comment]
@karlrupp Thanks for the documentation source.
