### ISSUE TITLE
Is ViennaCL matrix stored in a contiguous GPU memory block?

### ISSUE THREAD

**Issue by Kerkil** [viennacl/viennacl-dev#120]
I am using the memory handle returned by `A.handle().opencl_handle().get()` pointing to `viennacl::matrix<ScalarType> A`. When I initialize another memory object from another library, it looks like only the first row of `A` is being copied. Is ViennaCL matrix `A` residing in a contiguous GPU memory block?  

If matrix is not contiguous, what is the best way to copy the matrix into a contiguous memory block in ViennaCL (maybe, vector object)?

P.S. For some reason, I am not able to label the issue. The checkbox for selecting the issue to add labels is not visible to me.

**Comment by Kerkil** [comment]
Among a plethora of copy functions in ViennaCL, for some reason I have had difficulty finding a copy function for copying a ViennaCL matrix to a ViennaCL vector, both of which are in GPU. I am exploring this path with the assumption that `viennacl::vector<float>` is stored in a contiguous memory block. If my assumption is incorrect or if there are other better ways to obtain the matrix in a contiguous memory block please let me know.

**Comment by Kerkil** [comment]
I am trying to copy viennacl matrix to a vector column by column using `linalg::copy_vec.` However, despite that the range object (i.e., `aSub`) gets updated every iteration in for loop, only the first segment ( range from '0' to 'A.size1()'  in `a`)of `a` gets updated. What am I missing here?
```
void copy_matrix_to_vector(VCLMatrixType &A, VCLVectorType &a)
{
    // ViennaCL range object
    VCLRangeType lb=0, ub=A.size1();
    viennacl::range r(lb,ub);
    VCLVecRangeType aSub(a, r);

    viennacl::linalg::copy_vec(A, aSub, 0, 0, TRUE);
//  aSub = viennacl::column(A,i); // This doe work the same way as copy_vec
    for (int i=1; i<A.size2(); ++i)
    {
        lb=i*A.size1(), ub=(i+1)*A.size1()-1;
        r =viennacl::range(lb,ub);
        aSub = VCLVecRangeType(a, r);

        viennacl::linalg::copy_vec(A, aSub, 0, i, TRUE); // copy column i
    }

    std::cout << "a: " << a << std::endl;
}
```
Here is the output of the code snippet:
```
a: [336](-0.0528901,0.00229965,0.0298945,0.0382562,0.0341433,0.022892,0.00859183,-0.00575104,-0.0180603,-0.0270423,-0.0320554,-0.0329803,-0.0301074,-0.0240299,-0.0155478,-0.0055817,0.00490438,0.0149701,0.0237557,0.0305302,0.0347287,0.0359816,0.0341334,0.0292497,0.0216193,0.0117413,0.000306897,-0.0118328,-0.0237035,-0.0342588,-0.0424382,-0.0472362,-0.0477805,-0.0434195,-0.0338202,-0.0190758,0.000177419,0.0226339,0.0461818,0.067757,0.0831876,0.0870282,0.072385,0.0307304,-0.0482909,-0.177066,-0.370229,0.355118,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)
```

**Comment by karlrupp** [comment]
The memory layout for a matrix managed by ViennaCL is explained here:
http://viennacl.sourceforge.net/doc/manual-types.html#manual-types-matrix

If you wrap a given cl_mem device handle, then ViennaCL uses size1() == internal_size1() as well as size2() == internal_size2(). However, if ViennaCL allocates the memory, then usually size1() != internal_size1() and size2() != internal_size2().

**Comment by karlrupp** [comment]
Lables: Click on the gear icon near 'labels' and select "Question"

**Comment by karlrupp** [comment]
Data in a matrix is contiguous, but it may be padded if it is allocated by ViennaCL and no constraints on the internal sizes are specified (the default case). Most importantly, the line

    viennacl::matrix<T> B(user_cl_mem_obj, N, N);

wraps the user-provided OpenCL buffer, while the line

    viennacl::matrix<T> B = viennacl::matrix<T>(user_cl_mem_obj, N, N);

creates a temporary matrix wrapping the user-provided OpenCL buffer as a matrix and then *copies* the data into a ViennaCL-allocated matrix B, usually padded by zeros.

If you still want to 'pack' the matrix data into a single vector, wrap the underlying memory handle in a vector_base object, which you can then use like a vector:

     viennacl::vector_base<T> x(B.handle(), B.internal_size(), 0, 1);

However, I do not recommend to use this, because the new vector x has no mathematical relation to B.

**Comment by Kerkil** [comment]
@karlrupp Awesome. Thanks a lot for the good summary of the difference between the copy operations. I was able to "copy" the data between ArrayFire and ViennaCL successfully. Thanks again for the detailed explanation.
