### ISSUE TITLE
A missing template for fast_copy?

### ISSUE THREAD

**Issue by Kerkil** [viennacl/viennacl-dev#121]
The following code does not compile:

```
    #include "viennacl/matrix.hpp"   

   int main(){
       const std::vector<ScalarType> &vec(nr*nc)
       viennacl::matrix<ScalarType> A(nr, nc);

       viennacl::fast_copy(vec.begin(), vec.begin()+vec.size(), A);
       return 0;
    }
```
Here is the error message:
```
/Users/recondev/Projects/Linspace/main.cpp:567: error: no matching function for call to 'fast_copy'
    viennacl::fast_copy(vec.begin(), vec.begin()+vec.size(), A);
    ^~~~~~~~~~~~~~~~~~~
```

According to the documentation (http://viennacl.sourceforge.net/doc/blas3range_8cpp_source.html) - lines 159-161, I expect this to compile.

**Comment by karlrupp** [comment]
Nope, this should not compile, you instantiate a const-reference to a vector without initializing (first line in main()). This should work:

    int main(){
       std::vector<ScalarType> vec(nr*nc);
       viennacl::matrix<ScalarType> A(nr, nc);
       viennacl::fast_copy(&(vec[0]), &(vec[0])+vec.size(), A);
       return 0;
     }

It is important at this point to distinguish between pointers and iterators to make the overloads work correctly.
