### ISSUE TITLE
Iterative Solvers: Provide absolute tolerance

### ISSUE THREAD

**Issue by karlrupp** [viennacl/viennacl-dev#123]
Specifying only a relative tolerance may not meet all user demands, e.g. if the intial guess is already close to the solution.

**Comment by ddemidov** [comment]
This is more of a question than a suggestion: why not use relative tolerance w.r.t. norm of right-hand side? This is equivalent to norm of initial residual when initial approximation is zero, and behaves in the same way when a meaningful initial approximation is provided.

**Comment by karlrupp** [comment]
We already use the relative tolerance w.r.t. norm of the right hand side. With this ticket we also want to provide the ability to specify an absolute tolerance. This is handy in cases where e.g. you are solving a time-dependent system which does not change between two time steps, so your solution of the linear system is (close to) the zero vector.

**Comment by PhilippeTillet** [comment]
Why not also estimating the true residual error (
http://www.karlin.mff.cuni.cz/~strakos/download/2002_StTi.pdf) ? I remember
investigating it some time ago in python and it seemed to work fairly well
on my problems

**Comment by PhilippeTillet** [comment]
I'm also pretty curious, this seems like a powerful estimate but I have
never seen any implementation using it, which I think is a bit strange :O

**Comment by karlrupp** [comment]
@PhilippeTillet  What exactly are you referring to? We already keep track of the true residual error by using the respective recursion formulas.

**Comment by PhilippeTillet** [comment]
Oops, referring to the approximation of the true error (not residual :p):
||x - x_j||_A. Formula 4.9 in (
http://www.karlin.mff.cuni.cz/~strakos/download/2002_StTi.pdf)
