### ISSUE TITLE
Feature Request: Provide interface to Armadillo library

### ISSUE THREAD

**Issue by jeremysalwen** [viennacl/viennacl-dev#125]
The viennacl::copy functions do not work on Armadillo matrices.  It would be nice to provide this functionality.

**Comment by karlrupp** [comment]
Thanks for the feature request. I scheduled it for the next release (no promises, though...)

**Comment by jeremysalwen** [comment]
In the meantime, would there be a faster way than for loop assigment to copy over a matrix stored in dense column/row-major format like armadillo?

**Comment by cdeterman** [comment]
Are there any updates on this (confirmation on next release)?  This would be a great addition.  Also, is there a current workaround at the moment to copy armadillo matrices to the vienncl matrix objects?  I do a lot of work with Armadillo and preparing some code with a preliminary workaround in anticipation of full support would be ideal.

**Comment by karlrupp** [comment]
@cdeterman Yes, it will be part of the next release. I think I can even squeeze it in tomorrow.

**Comment by karlrupp** [comment]
Thanks for the feature request, bindings for Armadillo are now available. :-)
