### ISSUE TITLE
How to calculate sum in 1.6?

### ISSUE THREAD

**Issue by jeremysalwen** [viennacl/viennacl-dev#127]
http://sourceforge.net/p/viennacl/discussion/1143678/thread/38e942a0/
In this thread, is says that

>FYI: Actually, we have recently agreed to include additional reduction operations such as sum() in the upcoming 1.6.0 release.

However, I cannot seem to find out how to interface with these functions.  I can't seem to find a working sum() function in the documentation or code, and

    Scalar<double>  linalg::reduce<op_add>(vector);

gives compile errors

    ambiguous overload for ‘operator=’

**Comment by karlrupp** [comment]
Sorry for answering so late, I totally overlooked this :-/

reduce<> and friends are so far only prepared from the API point of view, but the implementations in the backends are still missing, i.e. they have (unfortunately) not made it into the 1.6.x release series. This is also the reason why you ran into the compilation issues.

As we've received a couple of requests regarding these reduction operations already, I scheduled this for the 1.7.0 release.
