### ISSUE TITLE
Random number generation?

### ISSUE THREAD

**Issue by jeremysalwen** [viennacl/viennacl-dev#128]
In this thread http://sourceforge.net/p/viennacl/discussion/1143678/thread/f6fe1301/ it seems that there is no functionality for generating vectors/matrices of random numbers.  Is there any suggested workaround for generating random numbers on the opencl device?

I am finding that copying the random numbers over is taking an excessive amount of time (I am generating a 784*784 matrix of booleans in my inner loop).

**Comment by PhilippeTillet** [comment]
Hello Jeremy,

It is not supported by ViennaCL right now. You may want to use an external
OpenCL RNG library (such as
http://cas.ee.ic.ac.uk/people/dt10/research/rngs-gpu-mwc64x.html) and
create a custom kernel.

Philippe
