### ISSUE TITLE
ViennaCL run-time error with OpenCL backend

### ISSUE THREAD

**Issue by ahazra** [viennacl/viennacl-dev#129]
I encountered the following error when I tried to run blas1.cpp in the tutorial folder in ViennaCL1.6.2 with OpenCL backend. It compiled perfectly with the following command:

           g++ blas1.cpp -DVIENNACL_WITH_OPENCL -lOpenCL

and then when I tried to run

      ./a.out

The following error is shown immediately

    Copying a few scalars...
Manipulating a few scalars...
operator +=
operator *=
operator -=
operator /=
operator +
multiple operators
mixed operations
CPU scalar s3: 42
GPU scalar vcl_s3: 42
a.out: /HOME/ahazra/libraries/include/viennacl/backend/memory.hpp:146: void viennacl::backend::memory_copy(const viennacl::backend::mem_handle&, viennacl::backend::mem_handle&, viennacl::vcl_size_t, viennacl::vcl_size_t, viennacl::vcl_size_t): Assertion `src_buffer.get_active_handle_id() == dst_buffer.get_active_handle_id() && bool("memory_copy() must be called on buffers from the same domain")' failed.
Aborted (core dumped)

Interestingly It ran successfully with OpenCL backend with many other tutorials, I did not check every tutorial yet. I am extremely new to GPU programming and library and I would be really happy if someone helps me out. Thank you in advance.

**Comment by karlrupp** [comment]
Thanks for the report. This looks like a bug on our side. I'll get back to you.

**Comment by karlrupp** [comment]
Fixed here: https://github.com/viennacl/viennacl-dev/commit/fadc5f2c5cc814d940c405060b62f4ceb4c3d487
