### ISSUE TITLE
Cuda Error while compiling a test program with ViennaCL

### ISSUE THREAD

**Issue by ahazra** [viennacl/viennacl-dev#130]
I am newbie in cuda programming. I was trying to use a library called ViennaCL which has GPU,OpenCL and Openmp backend. The programs in the tutorials worked fine with OpenCL but when I tried to compile following the procedure described in the software website, I received the following error message. Incientally, the program compiled and ran quiet well on the same day some time back . I could not figure out what went wrong.
I tried to compile with
/usr/local/cuda/bin/nvcc -DVIENNACL_WITH_CUDA -I/HOME/ahazra/libraries/include bisect.cu

and got the error message

'compute_10' and 'sm_10' architectures are deprecated, and may be removed in a future release.
/HOME/ahazra/libraries/include/viennacl/linalg/cuda/scalar_operations.hpp(88): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/scalar_operations.hpp(208): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/scalar_operations.hpp(332): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/scalar_operations.hpp(365): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(135): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(432): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(734): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(787): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(831): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(944): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(974): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(1004): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(1043): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(1070): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(1098): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(1126): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(1154): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(1182): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(1210): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(1238): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(1265): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(1294): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(1322): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(1350): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(1378): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(1406): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(1434): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(1462): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(1490): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(1673): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(1691): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(1709): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(1762): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(1794): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(2076): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(2096): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(2111): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(2128): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(2142): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(2156): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(2168): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(2180): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(2201): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(2233): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(2523): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(2542): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(2562): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(2792): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(2846): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(2962): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/vector_operations.hpp(3029): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(60): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(91): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(108): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(151): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(175): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(226): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(250): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(290): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(300): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(318): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(328): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(378): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(425): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(458): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(491): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(526): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(548): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(586): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(608): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(646): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(668): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(708): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(723): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(750): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(765): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(792): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(807): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(834): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(849): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(876): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(891): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(918): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(933): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(960): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(975): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(1002): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(1017): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(1044): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(1059): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(1086): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(1101): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(1128): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(1143): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(1170): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(1185): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(1212): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(1227): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(1254): error: kernel launches from templates are not allowed in system files

/HOME/ahazra/libraries/include/viennacl/linalg/cuda/matrix_operations.hpp(1269): error: kernel launches from templates are not allowed in system files

Error limit reached.
100 errors detected in the compilation of "/tmp/tmpxft_00006259_00000000-4_vector-range.cpp4.ii".
Compilation terminated.

What's going on here basically? what is the source of this sudden compilation error? Thank you in advance.

**Comment by karlrupp** [comment]
This is a CUDA limitation you can get around by not copying the ViennaCL source tree to system locations. Usually this is not a problem from your home directory, but for some reason your system considers /HOME/ahazra/libraries/include to be a system directory. You may want to check with your admin on what is going on, or just stick with OpenCL.

**Comment by ahazra** [comment]
Thank you for your response but I solved it already. Yes, true that was a problem with cuda. Somehow removing the variable CPLUS_INCLUDE_PATH from your environment i.e export CPLUS_INCLUDE_PATH=
and then it works.

**Comment by karlrupp** [comment]
Cool, thanks for also providing the solution :-)
