### ISSUE TITLE
Bug with CUDA backend for Armadillo Bindings?

### ISSUE THREAD

**Issue by cdeterman** [viennacl/viennacl-dev#135]
Using the armadillo example you have provided in the tutorials works fine if I don't modify it in any way.  However, I decided to try it using the CUDA backend.  So I added the following line to a copy of the file changed to .cu:

    #define VIENNACL_WITH_CUDA 1

I then try to compile with:
    
    nvcc -arch=sm_30 armadillo-with-viennacl.cu -I/path/to/viennacl

But this results in the following error:

>/usr/include/armadillo_bits/arma_static_check.hpp(23): error: const variable "junk" requires an initializer

>1 error detected in the compilation of "/tmp/tmpxft_000003bf_00000000-5_armadillo-with-viennacl.cpp4.ii".

Did I make a mistake somewhere in using the CUDA backend?

**Comment by karlrupp** [comment]
No, this is not a mistake on your side. From your error message it seems that nvcc is unable to compile Armadillo. I recommend submitting a bug report to the Armadillo developers.

**Comment by cdeterman** [comment]
Thanks, I will get in touch with the Armadillo developers and report back with any updates.

**Comment by cdeterman** [comment]
A quick update regarding this support.  I contacted the Armadillo developers who then directed me to NVIDIA.  Apparently it was an issue with the NVCC compiler where it didn't conform to the C++ standard causing some unforeseen consequences.  I submitted a bug report and I have been informed that a fix has been made and support will be available with the next CUDA release.

**Comment by karlrupp** [comment]
Thanks for the update! :-)
