### ISSUE TITLE
'Map' Eigen Classes in ViennaCL?

### ISSUE THREAD

**Issue by cdeterman** [viennacl/viennacl-dev#137]
Often times with Eigen it is nice to be able to use already mapped memory of an object instead of creating another copy.  Naturally I would like to be able to pass such objects to viennacl.  I create the following CUDA file where nearly everything is the same as normal Eigen Matrix objects except that I am trying to pass in a `Map<Matrix>` object.

When I try and compile just this CUDA file with NVCC (`nvcc -arch mapEigen.cu -I/viennacl/path -I/eigen/path -c`) I get essentially the same error four times (twice for each object) stating that the Eigen::Map class doesn't have the member 'size1' or 'size2'.  This looks more like a ViennaCL error than NVCC.  Is it something that isn't implemented with ViennaCL right now or did I miss something.

```cpp
#include <iostream>

// Eigen headers
#include <Eigen/Core>
#include <Eigen/Sparse>

// Use CUDA with ViennaCL
#define VIENNACL_WITH_CUDA 1

// Use ViennaCL algorithms on Eigen objects
#define VIENNACL_WITH_EIGEN 1

// ViennaCL headers
#include "viennacl/matrix.hpp"
#include "viennacl/linalg/prod.hpp"

using Eigen::Map;
using Eigen::MatrixXf;

extern "C"
Eigen::MatrixXf cu_vienna_sgemm(Map<MatrixXf> Am, Map<MatrixXf> Bm)
{
    int M = Am.cols();
    int K = Am.rows();
    int N = Bm.rows();
    int P = Bm.cols();

    viennacl::matrix<float> vcl_A(K,M);
    viennacl::matrix<float> vcl_B(N,P);
    viennacl::matrix<float> vcl_C(K,P);

    MatrixXf Cm(K, P);

    viennacl::copy(Am, vcl_A);
    viennacl::copy(Bm, vcl_B);

    vcl_C = viennacl::linalg::prod(vcl_A, vcl_B);

    viennacl::copy(vcl_C, Cm);

    return Cm;
}
```

**Comment by cdeterman** [comment]
I just verified the same thing happens if I try to use Map<Matrix> with the OpenCL backend.

**Comment by karlrupp** [comment]
Your are right: We have not provided any overloads for Map<MatrixXf>. Isn't there a possibility to wrap a buffer object into a 'normal' Eigen matrix?

**Comment by cdeterman** [comment]
Technically I could but I am trying to also work with objects that can be very large and it is much more preferred to refer to the already mapped memory.  I need to sometimes create an Eigen matrix from a pointer my understanding is that by using a 'normal' Eigen matrix it would create a separate object as opposed to using the previously mapped memory as you would with a 'Map' Eigen matrix.  I would like to avoid copying objects as much as possible.

**Comment by cdeterman** [comment]
Would this be quite a large undertaking?  I don't mean to prod you and there isn't any rush.  I just want to know if this is something you would like to eventually extend or if you don't think it is worthwhile or perhaps know of another workaround in the mean time.

**Comment by karlrupp** [comment]
I think that this is only a matter of another function overload (reusing the existing implementation), if Map<Matrix> provides the same interface as Matrix. Let me have a look tomorrow, I'll report back.

**Comment by cdeterman** [comment]
@karlrupp I'm sure you are quite busy but did you happen to have a chance to have a look at the prospect of adding the Map overloads?

**Comment by karlrupp** [comment]
gosh, indeed I missed this, sorry. I'll take care of it tomorrow morning.

**Comment by karlrupp** [comment]
Support for Eigen::Map<> for matrices is now available here:
https://github.com/viennacl/viennacl-dev/commit/32ff50246c577d95a3ec0d31ca5f36d21eed5dc1

Any feedback is appreciated. Is the same needed for vectors?

**Comment by cdeterman** [comment]
@karlrupp Sorry for slow response, just finally got to testing this out.  Everything appears to be working great. The same support for vectors would definitely be appreciated :-)

Are these additions intended to be part of 1.7.0?

**Comment by karlrupp** [comment]
Thanks for the feedback. I'll add similar overloads for vectors then - should not be a big deal.

Yes, these are going to be part of 1.7.0. The release will take about two more weeks (too many other things coming in on short notice recently...)

**Comment by karlrupp** [comment]
Alright, the vector overloads are now available too.

@cdeterman : If you run into issues, please let me know, otherwise please close this issue :-)
