### ISSUE TITLE
Error running improved lanczos.cpp example 

### ISSUE THREAD

**Issue by ramirezaa** [viennacl/viennacl-dev#138]
I try to compile the improved "lanczos.cpp" examples which returns eigenvalues and eigenvectors but I keep getting the same error: 
```
viennacl/linalg/lanczos.hpp:456:86: error: no matching function for call to ‘project(viennacl::matrix<float, viennacl::column_major>&, viennacl::range, viennacl::range)
```

Was the "project" function supposed to be included?

**Comment by karlrupp** [comment]
Yes, you are correct. Fixed here: https://github.com/viennacl/viennacl-dev/commit/96e20b38b83254c57d37d0a1e9c876aeb067ddbf
Thanks for reporting!

**Comment by ramirezaa** [comment]
Thank you! That works! I also do not know if this is a big deal but on line 59, it seems like the test file directory should be changed to: 
```
../testdata/mat65k.mtx
```

I kept getting an error due to an incorrect file path. 

Thanks again!

**Comment by karlrupp** [comment]
Thanks for the feedback, ramirezaa.
With regard to the matrix file: That depends on the current working directory. In the manual we state that all examples should be run from the build/ folder, in which case the file is found.

**Comment by ramirezaa** [comment]
Of course! Thank you for that information.
