### ISSUE TITLE
Looping over an array using tile blocking

### ISSUE THREAD

**Issue by mchandra** [viennacl/viennacl-dev#140]
Hi,

How do I convert the following loops into viennacl? :

```
int N1 = 128, N2 = 128;

int tileSize1 = 16, tileSize2 = 16;

double A[N2][N1];

for (int jTile=0; jTile<N2/tileSize2; jTile++)
{
  for (int iTile=0; iTile<N1/tileSize1; jTile++)
  {
    double tile[tileSize2][tileSize1];

    for (int jInTile=0; jInTile<tileSize2; jInTile++)
    {
      for (int jInTile=0; jInTile<tileSize2; jInTile++)
      {
        /* Load chunks of A into tile. Equivalent to filling up _local_ memory in opencl */  
      }
    }
    
    /* In opencl, wait for the threads to write to _local_ memory using barrier(CLK_LOCAL_MEM_FENCE) */

    for (int jInTile=0; jInTile<tileSize2; jInTile++)
    {
      for (int jInTile=0; jInTile<tileSize2; jInTile++)
      {
        /* Do computation on tile */  
      }
    }
  }
}
```

Thanks,
Mani

**Comment by karlrupp** [comment]
Hi Mani,
ViennaCL doesn't wrap such low-level kernel details in any way. That is, you would just fill out the details in the kernel and launch the kernel with data from ViennaCL objects. ViennaCL's strenghts are in providing lots of built-in kernels for common operations (say, BLAS-like) and algorithms (say, LAPACK-like) from a C++ interface similar to other linear algebra libraries without requiring the user to get into low-level kernel details.

Hope this helps :-)

**Comment by mchandra** [comment]
Ah. I was hoping to use viennacl to do something like the above. The reason is I want the code to be universal, i.e. use opencl if available but otherwise switch to openmp. The lack of opencl on many clusters is an issue.

**Comment by karlrupp** [comment]
I was looking into ways of accomplishing the same, but ultimately I had to accept that such an approach would restrict us in achieving good performance. Have a look at libocca if you still want to go down that road: http://libocca.org/

**Comment by mchandra** [comment]
Thank you for the ref. That is exactly what I was looking for.

**Comment by karlrupp** [comment]
You're welcome!
