### ISSUE TITLE
How to find smallest eigenvalues for sparse matrix with ViennaCL?

### ISSUE THREAD

**Issue by ramirezaa** [viennacl/viennacl-dev#141]
Is there a way to calculate the smallest eigenvalue/eigenvector of a sparse matrix? I know if I want to calculate the *N-th* eigenvalue/eigenvector with the highest magnitudes I can simply use *Lanczos* algorithm; but now I want to find the smallest eigenvalue/eigenvectors.

Any suggestions will be greatly appreciated.

**Comment by karlrupp** [comment]
(I assume you are referring to the smallest eigenvalue in modulus)
A common technique for this is by inverse power iteration, i.e. repeated solutions of systems Ay_i = z_i with suitable right hand sides z_i. Thus, finding the smallest eigenvalue is more expensive than solving a system of linear equations. In terms of computational effort it is often most efficient to use a sparse direct solver, factor A into LU, and then quickly solve the systems mentioned above. However, ViennaCL doesn't provide any sparse direct solvers and no ready-to-go inverse power iteration (yet).

**Comment by ramirezaa** [comment]
Thank you for that information. I found a header only version of a library called RedSVD which does the following:

>redsvd is a library for solving several matrix decompositions including singular value decomposition (SVD), principal component analysis (PCA), and eigen value decomposition. redsvd can handle very large matrix efficiently, and optimized for a truncated SVD of sparse matrices. For example, redsvd can compute a truncated SVD with top 20 singular values for a 100K x 100K matrix with 1M nonzero entries in less than one second.

But it doesn't directly state if it finds the smallest eigenvalue in modulus. Out of curiosity, do you have any libraries in mind that could help me with the computation of the smallest eigenvalue in modulus?

**Comment by skn123** [comment]
Hey Karl :)
Looks like this question has resurrected the feature for which we had exchanged e-mails a couple of years back !! 
ramirezaa, Would you like to implement this feature in ViennaCL?

**Comment by karlrupp** [comment]
@ramirezaa : Computing the largest eigenvalues/singular values is indeed simpler, cf. RedSVD. Maybe MAGMA has something suitable for your needs: http://icl.cs.utk.edu/magma/

@skn123 : Yeah, SVD-related questions indeed come up occasionally...

**Comment by skn123** [comment]
@karlrupp Sadly not for Sparse matrices. We can compute them for Dense only. @ramirezaa try and see if you can convert your problem from finding smallest eigenvalues to that of finding largest eigenvalues

**Comment by PhilippeTillet** [comment]
Hey,

In order to find the smallest Eigenvalue, you should be able to use the
power iteration with a linear solver called at each iteration. ViennaCL
provides very good solvers for sparse matrices.

**Comment by ramirezaa** [comment]
@skn123 It would be a good idea to implement an SVD feature for ViennaCL but I do not know if my inexperience with all the supported parallel programming hardware would allow me to write a good implementation of SVD for ViennaCL.

Additionally, I ended up using a repo found here: https://github.com/beam2d/arpaca that uses ARPACK  in order to find smallest/greatest eigenvalues/vectors from sparse matrices.

Thanks for all the suggestions and sorry for the late response.
