### ISSUE TITLE
qr_method example doesn't compile with 'double' ScalarType

### ISSUE THREAD

**Issue by cdeterman** [viennacl/viennacl-dev#145]
The [qr_method.cpp](https://github.com/viennacl/viennacl-dev/blob/master/examples/tutorial/qr_method.cpp) example compiles fine with it working only with `float` but if I change the `float` to `double` as noted in the comments the compiler fails.  It looks like there aren't the corresponding `double` internal functions provided.

g++ qr_method.cpp -o qr_method -I/path/to/viennacl

>In file included from qr_method.cpp:36:0:
/home/cdeterman/viennacl-dev/viennacl/linalg/qr-method.hpp: In instantiation of ‘void viennacl::linalg::detail::hqr2(viennacl::matrix<ScalarType, viennacl::row_major>&, viennacl::matrix<ScalarType, viennacl::row_major>&, VectorType&, VectorType&) [with SCALARTYPE = double; VectorType = std::vector<double>]’:
/home/cdeterman/viennacl-dev/viennacl/linalg/qr-method.hpp:768:38:   required from ‘void viennacl::linalg::detail::qr_method(viennacl::matrix<ScalarType, viennacl::row_major>&, viennacl::matrix<ScalarType, viennacl::row_major>&, std::vector<RowType>&, std::vector<RowType>&, bool) [with SCALARTYPE = double]’
/home/cdeterman/viennacl-dev/viennacl/linalg/qr-method.hpp:813:39:   required from ‘void viennacl::linalg::qr_method_sym(viennacl::matrix<ScalarType, viennacl::row_major>&, viennacl::matrix<ScalarType, viennacl::row_major>&, std::vector<RowType>&) [with SCALARTYPE = double]’
qr_method.cpp:109:58:   required from here
/home/cdeterman/viennacl-dev/viennacl/linalg/qr-method.hpp:528:73: error: no matching function for call to ‘update_float_QR_column(viennacl::linalg::detail::FastMatrix<double>&, std::vector<float>&, int&, int&, int&, bool)’
                 update_float_QR_column<SCALARTYPE>(H, buf, m, n, n, true);
                                                                         ^
/home/cdeterman/viennacl-dev/viennacl/linalg/qr-method.hpp:528:73: note: candidate is:
/home/cdeterman/viennacl-dev/viennacl/linalg/qr-method.hpp:145:10: note: template<class SCALARTYPE, class MatrixT> void viennacl::linalg::detail::update_float_QR_column(MatrixT&, const std::vector<RowType>&, int, int, int, bool)
     void update_float_QR_column(MatrixT& A,
          ^
/home/cdeterman/viennacl-dev/viennacl/linalg/qr-method.hpp:145:10: note:   template argument deduction/substitution failed:
/home/cdeterman/viennacl-dev/viennacl/linalg/qr-method.hpp:528:73: note:   cannot convert ‘buf’ (type ‘std::vector<float>’) to type ‘const std::vector<double>&’
                 update_float_QR_column<SCALARTYPE>(H, buf, m, n, n, true);

**Comment by cdeterman** [comment]
I also discovered that even with `float`, if I include the `matrix.hpp` file the compilation will also fail.  This struck me as strange since I would think the `matrix.hpp` file could be included anywhere but perhaps I am misunderstanding something about the structure of viennacl.

added line

`#include "viennacl/matrix.hpp"`

Output from g++

>In file included from /home/cdeterman/viennacl-dev/viennacl/linalg/matrix_operations.hpp:38:0,
                 from /home/cdeterman/viennacl-dev/viennacl/matrix.hpp:28,
                 from qr_method.cpp:35:
/home/cdeterman/viennacl-dev/viennacl/linalg/host_based/matrix_operations.hpp: In instantiation of ‘void viennacl::linalg::host_based::house_update_QL(viennacl::matrix_base<T>&, viennacl::vector_base<T>&, viennacl::vcl_size_t) [with NumericT = float; viennacl::vcl_size_t = long unsigned int]’:
/home/cdeterman/viennacl-dev/viennacl/linalg/matrix_operations.hpp:1017:68:   required from ‘void viennacl::linalg::house_update_QL(viennacl::matrix_base<T>&, viennacl::vector_base<T>&, viennacl::vcl_size_t) [with NumericT = float; viennacl::vcl_size_t = long unsigned int]’
/home/cdeterman/viennacl-dev/viennacl/linalg/qr-method.hpp:707:56:   required from ‘bool viennacl::linalg::detail::householder_twoside(viennacl::matrix_base<T>&, viennacl::matrix_base<T>&, viennacl::vector_base<T>&, viennacl::vcl_size_t) [with SCALARTYPE = float; viennacl::vcl_size_t = long unsigned int]’
/home/cdeterman/viennacl-dev/viennacl/linalg/qr-method.hpp:722:51:   required from ‘void viennacl::linalg::detail::tridiagonal_reduction(viennacl::matrix_base<T>&, viennacl::matrix_base<T>&) [with SCALARTYPE = float]’
/home/cdeterman/viennacl-dev/viennacl/linalg/qr-method.hpp:753:43:   required from ‘void viennacl::linalg::detail::qr_method(viennacl::matrix<ScalarType, viennacl::row_major>&, viennacl::matrix<ScalarType, viennacl::row_major>&, std::vector<RowType>&, std::vector<RowType>&, bool) [with SCALARTYPE = float]’
/home/cdeterman/viennacl-dev/viennacl/linalg/qr-method.hpp:813:39:   required from ‘void viennacl::linalg::qr_method_sym(viennacl::matrix<ScalarType, viennacl::row_major>&, viennacl::matrix<ScalarType, viennacl::row_major>&, std::vector<RowType>&) [with SCALARTYPE = float]’
qr_method.cpp:110:58:   required from here
/home/cdeterman/viennacl-dev/viennacl/linalg/host_based/matrix_operations.hpp:1668:26: error: ‘prod’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
    Q = prod(Q_temp, vcl_P);
                          ^
In file included from qr_method.cpp:36:0:
/home/cdeterman/viennacl-dev/viennacl/linalg/prod.hpp:355:5: note: ‘template<class SparseMatrixType, class NumericT> viennacl::vector_expression<const SparseMatrixType, const viennacl::vector_base<NumericT>, viennacl::op_prod> viennacl::linalg::prod(const SparseMatrixType&, const viennacl::vector_base<NumericT>&)’ declared here, later in the translation unit
     prod(const SparseMatrixType & A,
     ^

**Comment by karlrupp** [comment]
Thanks for reporting. Let me look into it.

**Comment by karlrupp** [comment]
Only a one-line change was needed -> fixed. Thanks again for reporting!

**Comment by cdeterman** [comment]
Thanks, it does indeed compile for `double` now.  However, it still does fail to compile if `#include "viennacl/matrix.hpp"` is included.  Is there a reason it shouldn't be included?

**Comment by karlrupp** [comment]
There was no reason why matrix.hpp should not be included. I just pushed a fix.

**Comment by cdeterman** [comment]
Excellent, everything is now compiling without errors :)
