### ISSUE TITLE
Could NOT find OPENCL (missing:  OPENCL_INCLUDE_DIR)

### ISSUE THREAD

**Issue by sunshineatnoon** [viennacl/viennacl-dev#156]
I manually set OPENCL path by
```
cmake .. -DOPENCL_INCLUDE_DIR=../CL
```
but it still gives me this error:
```
Could NOT find OPENCL (missing:  OPENCL_LIBRARY) 
```
how can I solve this problem?

**Comment by karlrupp** [comment]
The OPENCL_LIBRARY refers to the dynamic OpenCL library (libOpenCL.so on Linux, OpenCL.lib on Windows). You need to provide the path to the respective (vendor-)SDK. If you don't need the OpenCL-backend, disable it using `-DENABLE_OPENCL=Off`

**Comment by sunshineatnoon** [comment]
I wanted to install viennacl to run an opencl framework, I manually copied the header files into /usr/local/include, now it works fine, thanks!
