### ISSUE TITLE
fast_copy from ViennaCL to Eigen memory error?

### ISSUE THREAD

**Issue by cdeterman** [viennacl/viennacl-dev#161]
Experimenting with `fast_copy` I took a copy of the `eigen-with-viennacl.cpp` file from the examples.  I make a single change on line 174 from

    viennacl::copy(vcl_densemat, eigen_densemat2);

to

    viennacl::fast_copy(vcl_densemat, eigen_densemat2.data());

This change compiles but I get the following error:

>----------------------------------------------
## Single precision
----------------------------------------------
VCL sparsematrix dimensions: 6, 5
Difference for dense matrix-vector product: 0
Difference for dense matrix-vector product (Eigen->ViennaCL->Eigen): 0
Difference for sparse matrix-vector product: 0
Difference for sparse matrix-vector product (Eigen->ViennaCL->Eigen): 0
*** Error in `./eigen_test': free(): invalid pointer: 0x00000000021eb6f0 ***
Aborted (core dumped)

Did I miss something in the use of `fast_copy`?

**Comment by karlrupp** [comment]
Yes: The matrix may be padded (currently up to multiples of 128):
http://viennacl.sourceforge.net/doc/manual-types.html#manual-types-matrix
Since Eigen never pads matrices, a vanilla use of fast_copy() almost always leads to such memory errors.

**Comment by cdeterman** [comment]
Thank you, that clarifies that point but I have another related issue with copying data from cpu to gpu with 'mapped' eigen matrices.

Using the same example file I just add the following and replace any future `eigen_densemat` with `eigen_densemat_map`.

    Eigen::Map<EigenMatrix> eigen_densemat_map(eigen_densemat.data(), 6, 5);

This compiles fine and I can run it without error.  However, if I try to use `fast_copy`:

    viennacl::fast_copy(eigen_densemat_map.data(), eigen_densemat_map.data() + eigen_densemat_map.size(), vcl_densemat);

Printing out the viennacl matrix now shows:

    [6,5]((2,-1,0,0,0),(0,0,0,0,0),(0,0,0,0,0),(0,0,0,0,0),(0,0,0,0,0),(0,0,0,0,0))

This doesn't happen if I use the normal `copy` or if I use non-mapped matrices.

**Comment by karlrupp** [comment]
The reason for the behavior with mapped matrices is similar to the one above: If you use fast_copy() with a ViennaCL matrix as destination, then the data you supply via the first argument needs to *exactly* match the memory layout of the ViennaCL matrix. This in particular includes the padding with zeros.

**Comment by cdeterman** [comment]
Could you explain why the non-mapped eigen matrix works with `fast_copy` but not with the mapped matrix?  I understand the padded limitation but I am confused why it works with a normal eigen matrix then.  I just want to understand what difference there is.  Thanks

**Comment by karlrupp** [comment]
As far as I can tell, neither of the two cases should work with fast_copy(). Could you please send me a small example or instructions on how to reproduce?

**Comment by cdeterman** [comment]
After trying to reproduce I realized there was a plain `copy` still present after I was did the plain eigen matrix `fast_copy` which was giving the impression that the `fast_copy` was working.  My mistake, thank you for your responses.  I will let this go now as everything makes sense to me now.  Apologies for making this issue run on.

**Comment by karlrupp** [comment]
No worries - and please don't be afraid to ask questions whenever something is not clear. This also helps us with improving our documentation, resolve pitfalls, etc. Thank you :-)
