### ISSUE TITLE
Set Diagnonal Elements?

### ISSUE THREAD

**Issue by cdeterman** [viennacl/viennacl-dev#165]
Is there a way to set diagonal elements?  I know I can extract diagonal elements with:

    viennacl::diag(vcl_A);

but what if I want to set all diagonal elements to 0?

**Comment by karlrupp** [comment]
There is an indirect way by using vector_base:

    // row-major matrices:
    viennacl::vector_base<T> diag_A(vcl_A.handle(), vcl_A.size1(), 0, vcl_A.internal_size2() + 1);

    // column-major matrices:
    viennacl::vector_base<T> diag_A(vcl_A.handle(), vcl_A.size1(), 0, vcl_A.internal_size1() + 1);

You can then manipulate `diag_A` like any other vector of values. The way this works is: Take the memory buffer `vcl_A.handle()` from the matrix, interpret as a vector of `vcl_A.size1()` values, starting at element `0` and an increment of `vcl_A.internal_size1/2() + 1` values (i.e. one row/column plus one element). If your matrix is non-square, you may need to replace `vcl_A.size1()` with `min(vcl_A.size1(), vcl_A.size2())`

**Comment by cdeterman** [comment]
That works great, thanks.
