### ISSUE TITLE
Undefined conversion of float INFINITY to int

### ISSUE THREAD

**Issue by nhaustov** [viennacl/viennacl-dev#167]
Some ViennaCL kernels use the following pattern:
__kernel void _norm_inf_0(unsigned int N,__global int* obj2_temp,__global int* obj0_pointer,__global int* obj1_pointer,unsigned int obj1_start,unsigned int obj1_stride)
{
...
    int obj2_acc = -INFINITY;
    for(unsigned int i = get_global_id(0); i < N/1; i += get_global_size(0))
    {
        int obj1reg = (obj1_pointer)[i*obj1_stride];
        obj2_acc=max(obj2_acc,(int)(abs(obj1reg)));
...

Looking at OpenCL C spec and C99 spec, the result of conversion of value that cannot be represented is undefined. Most compilers will saturate the value to -2^31+1, however very recent clang emits undef for obj2_acc.

The goal of the code is to initialize obj2_acc with minimal value for the type. For int, the value of -2^31+1 can be used as the first value.

**Comment by karlrupp** [comment]
Thanks for the feedback. We are about the replace these types of kernels with a variant that does not exhibit this problem (branch karlrupp/feature-reduce-generator-usage). It should make it to master in the next couple of days.
