### ISSUE TITLE
Initialize matrices with single value

### ISSUE THREAD

**Issue by cdeterman** [viennacl/viennacl-dev#173]
I know we can initial a matrix of zeros with `viennacl::zero_matrix`.  Is there a method to initialize of matrix of a user supplied number (e.g. a matrix of 2's)?  It would be convenient to not need to loop through a `viennacl::matrix` to fill it with initial values.

**Comment by karlrupp** [comment]
Yes, there is:

    viennacl::scalar_matrix<T>(N, M, initial_value);

http://viennacl.sourceforge.net/doc/manual-types.html#manual-operations-initializers
