### ISSUE TITLE
Pass-by-Reference methods (i.e. 'in-place')?

### ISSUE THREAD

**Issue by cdeterman** [viennacl/viennacl-dev#177]
Right now it appears that most [BLAS 1 operation](http://viennacl.sourceforge.net/doc/manual-operations.html) require the declaration of a second object to contain the results.  For example:

    // second object
    y = element_sin(x);

It would be useful if most of the functions would have a method to pass the value by reference similar to the AXPY method

    x *= alpha;

I imagine this would be a `void` implementation where the call would be

    element_sin(x);

alternately does the following avoid extra temporary objects?  If so, this issue could likely be closed.

    x = element_sin(x);

wherein the elements of `x` are altered in place.  Naturally this isn't really possible for all BLAS operations but many operations could definitely benefit from this.  The focus here clearly being a performance concern where it is common-place in C++ to pass by reference and alter objects without unnecessary copies.

**Comment by karlrupp** [comment]
Yes, in-place operations work just as you expected, e.g.

    x = element_sin(x);  // no temporary
    x = 2.0 * x;         // no temporary
    x = prod(A, x);      // with temporary, because this is necessary for a correct result

While you are right that a second object is required, there is no requirement that the objects need to be distinct.
