### ISSUE TITLE
Benchmarks for dense OpenCL GEMM, vs eg clBLAS?

### ISSUE THREAD

**Issue by hughperkins** [viennacl/viennacl-dev#186]
Hi,

Do you have any benchmarks for dense OpenCL GEMM, vs eg clBLAS?

**Comment by karlrupp** [comment]
Here is a relevant benchmark application:
https://github.com/viennacl/viennacl-dev/blob/master/examples/benchmarks/dense_blas.cpp
(build via CMake with `make dense_blas-bench-opencl`)

I don't have a complete set of benchmarks vs. clBLAS at hand, though.

**Comment by hughperkins** [comment]
> I don't have a complete set of benchmarks vs. clBLAS at hand, though.

Ok, understood.  Question: what do you see as key advantages of viennacl compared to clblas, for dense GEMM?

**Comment by karlrupp** [comment]
Depends on your prerequisites. If you are only looking for GEMM on AMD GPUs, there's probably no significant advantage. If you are looking for performance portability within OpenCL, then you may see better performance of ViennaCL on e.g. NVIDIA devices. If you don't want to be restricted to OpenCL, then ViennaCL allows you to use the same code base also for CUDA and OpenMP :-)

**Comment by hughperkins** [comment]
Cool.  Thank you Karl :-)
