### ISSUE TITLE
sparse_prod-test: Sparsity pattern mismatch

### ISSUE THREAD

**Issue by leviat** [viennacl/viennacl-dev#189]
I just ran the sparse_prod-test in the master branch and for double value types a pattern mismatch occurred. This is not supposed to happen, is it?
This happens with both opencl enabled and disabled. I appended the console's log.
My pc configuration is:

Intel Xeon E5540
Geforce GTX 780 Ti (driver ver. 353.90)
12 GB RAM
Windows 7

[sparse_prod-test-opencl.txt](https://github.com/viennacl/viennacl-dev/files/327669/sparse_prod-test-opencl.txt)

**Comment by karlrupp** [comment]
Thanks for reporting! It's strange that the single precision tests pass and the double precision tests don't, because it's using the same (templated) code. Is this reproducible, or did this just happen once?

**Comment by leviat** [comment]
Sorry for the late reply. The problem has been reproducible on the machine when I ran the tests. Someone is currently blocking the only machine in our office with OpenCL installed so I can't say if the mismatches are in the same entries but afaik they should be.

If there is anything I can do to help tracking the source of this error, I'd be glad to help.
