### ISSUE TITLE
Sparse Matrix - Sparse Matrix Product: CL_OUT_OF_RESOURCES

### ISSUE THREAD

**Issue by leviat** [viennacl/viennacl-dev#190]
I have a big sparse matrix C with roughly 600k rows, 1m columns and 4m nonzero entries. With that matrix, I wanted to compute C \* C^t. However during computation on the GPU, I get a CL_OUT_OF_RESOURCES error. Computation on the CPU takes less than 2 GB memory so I doubt it failed because of memory limitations. I also shrinked the matrix to half its size for testing purposes but the error still occurred. Did I forget to set something up properly or is my matrix just too big for the GPU.

My configuration
Intel Xeon E5540
12 GB RAM
Geforce GTX 780 Ti  3GB (driver ver. 353.90)
Windows 10

Code: 

``` C++

void SetupMatrices() {

  size_t numOfRows = 637375;
  size_t numOfColumns = 957808;
  std::vector< std::map< unsigned int, ScalarType> > cpu_sparse_matrix;
  cpu_sparse_matrix.resize(numOfRows);

  AddConstraints(cpu_sparse_matrix); // adds 3978920 nonzero entries

  std::vector< std::map< unsigned int, ScalarType> > cpu_sparse_matrix_transposed = TransposedMatrix(cpu_sparse_matrix, numOfColumns); //just a function to transpose our map

  // Setup sparse matrices
  viennacl::compressed_matrix<ScalarType, 1U> vcl_sparse_matrix(numOfRows, numOfColumns);
  viennacl::compressed_matrix<ScalarType, 1U> vcl_sparse_matrix_transposed(numOfColumns, numOfRows);

  //copy to OpenCL device:
  copy(cpu_sparse_matrix, vcl_sparse_matrix);
  copy(cpu_sparse_matrix_transposed, vcl_sparse_matrix_transposed);


  viennacl::compressed_matrix<ScalarType> CCT = viennacl::linalg::prod(vcl_sparse_matrix, vcl_sparse_matrix_transposed); // ==> CL_OUT_OF_RESOURCES

}

```

**Comment by karlrupp** [comment]
If the computational succeeds on the CPU and you obtain a CL_OUT_OF_RESOURCES on the GPU, it's likely that the matrix is just too big. I ran into memory errors already at matrices of smaller dimension during the testing and benchmarking. The product of two sparse matrices can even be a dense matrix in worst case...
