### ISSUE TITLE
85MB of doc in the download :-O

### ISSUE THREAD

**Issue by hughperkins** [viennacl/viennacl-dev#192]
The download is ~8.5MB, which seems a bit excessive?  The git clone is also pretty huge.  Maybe it could be worth considering moving the doc to a separate repo?

**Comment by karlrupp** [comment]
If you want to grab only a certain subset, you can always check out a part of the source tree from this repository.

**Comment by hughperkins** [comment]
That would be true in svn. It's not true of git.  Not that I'm recommending svn; I prefer git a hundred times over. But git doesnt let you check out a part of the source tree, as far as I know?
