### ISSUE TITLE
12MB of testdata in the repo?

### ISSUE THREAD

**Issue by hughperkins** [viennacl/viennacl-dev#193]
viennacl download is huge.  This is I think partly because of the 12MB of testdata?  Perhaps this could be moved to a separate download, and out of hte repo?

**Comment by karlrupp** [comment]
Moving it out of the repo is not possible without destroying the history (and all associated commit hashes). I agree that a separate testing repository would have been a better pick, but it's too late to do so now.

**Comment by hughperkins** [comment]
It's actually possible to rewrite history, though it does involve a force-push.
