### ISSUE TITLE
Is libOpenCL.so dynamic linked?

### ISSUE THREAD

**Issue by kris-hu** [viennacl/viennacl-dev#197]
@karlrupp 
Hi, I'm a beginner to ViennaCL and here's a question that confused me.
My environment is ubuntu14.04 64-bit and Intel® Core™ i7-4770 CPU. I downloaded the Intel opencl backend from https://software.intel.com/en-us/articles/opencl-drivers#latest_linux_driver.
I just created a link under /usr/lib to the Intel libOpenCL.so, it could pass cmake and make, and the tutorials ran successfully. However, when libOpenCL.so was removed, the tutorials could also run successfully.
This confused me, is libOpenCL.so dynamic linked or static linked?

Best Regards,
Kris

**Comment by karlrupp** [comment]
Hi Kris,
chances are that your libOpenCL.so in the Intel SDK is also registered via either the OpenCL ICD in `/etc/OpenCL/vendors/`, or via the LD_LIBRARY_PATH environment variable. Issue

    ldd examples/tutorial/viennacl-info

(or similar for the executable under question) to list the shared libraries used for an executable.

Best regards,
Karli

**Comment by kris-hu** [comment]
Yes, I found there's two libOpenCL.so in my PC.
Thanks very much for your help, Karli.
