### ISSUE TITLE
Device Type Mappings?

### ISSUE THREAD

**Issue by cdeterman** [viennacl/viennacl-dev#208]
Is there a mapping of device types?  I normally have been assigning the results of:

```c++
 switch(devices[id].type()){
            case 2: 
                device_type[id] = "cpu";
                break;
            case 4: 
                device_type[id] = "gpu";
                break;
            case 8: 
                device_type[id] = "accelerator";
                break;
            default:
                std::cout << "unrecognized device" << std::endl;
```

However, after experimenting with the [pocl driver](http://portablecl.org/) I am getting the message 'unrecognized device' where the type is '3'.  Do you have a mapping the would identify this?  I thought it would be the OpenCL mappings for `CL_DEVICE_TYPE` but I don't see anything matching '8' for 'CL_DEVICE_TYPE_GPU` so I'm not sure where the mappings come from here.

**Comment by cdeterman** [comment]
I suspect that this is a pocl related problem which I have submitted [here](https://github.com/pocl/pocl/issues/393) but weren't sure if you were familiar either.

**Comment by cdeterman** [comment]
It appears that I was not aware the the OpenCL device types are bitfield types so they can represent multiple types (such as `CL_DEVICE_TYPE_DEFAULT` and `CL_DEVICE_TYPE_CPU`) hence the three.  By using the bit operators `&` the problem is solved.

**Comment by karlrupp** [comment]
yes, the device types are bit fields. Most OpenCL SDKs don't use it this way and only set a single bit. :-)
