### ISSUE TITLE
Update only coefficients of a sparse matrix

### ISSUE THREAD

**Issue by jdumas** [viennacl/viennacl-dev#214]
Hi,

I have a sparse matrix in CRS format that I want to transfer from the CPU to the GPU using ViennaCL. During computation, I need to update the coeffcients of the sparse-matrix, but without changing its sparsity pattern. Is there a way to update only the buffer of elements in a sparse matrix in ViennaCL?

Moreover, I was wondering if there was a low-level `copy()` function for `viennacl::compressed_matrix<T>`, that could take 3 pointers to a matrix in CRS format? The requirements from the [documentation](http://viennacl.sourceforge.net/doc/manual-types.html#manual-types-sparse-compressed-usage) seem a bit heavy as one need to provide a custom data type. For example, Eigen provides a low-level API to access the pointers of the CRS format directly:

    sm1.valuePtr();      // Pointer to the values
    sm1.innerIndextr();  // Pointer to the indices.
    sm1.outerIndexPtr(); // Pointer to the beginning of each inner vector

Would it be possible to implement the `copy()` function without duplicating the CPU matrix on the host memory (as this [seems to be](https://github.com/viennacl/viennacl-dev/blob/a50be8202f67a968c356d687bdd553576b6a7f60/viennacl/compressed_matrix.hpp#L256) done in the current implementation)?

**Comment by karlrupp** [comment]
Hey,

I just added support for directly passing CSR data from your arrays:
https://github.com/viennacl/viennacl-dev/commit/f7f7be2287e5575711b54456ca4aaa2e340dd2af
See the comments and changes in sparse.cpp for usage.

Do you also need the copy back from a `viennacl::compressed_matrix`?

**Comment by jdumas** [comment]
Nice! In my case I don't need to copy back the information (since I just mostly need the result from a spmv operation).

However, do you think it is possible to copy only the array of nnz coefficients? I need to regularly update a matrix without changing its sparsity pattern, and I think it could help saving more bandwith.

**Comment by karlrupp** [comment]
You can update the nonzero values with just a single line, see here:
https://github.com/viennacl/viennacl-dev/blob/master/viennacl/compressed_matrix.hpp#L888
Pull out the `elements_` member via the public `.handle()` member function.

Please let me know if you encounter problems.

**Comment by jdumas** [comment]
Thanks! I'll try that and let you know how it goes.

**Comment by jdumas** [comment]
Seems to be working fine! I'll close this issue.
