### ISSUE TITLE
Accessing column of matrix without copy?

### ISSUE THREAD

**Issue by cdeterman** [viennacl/viennacl-dev#221]
Is it possible to access a column (or row for that matter) of a `matrix` without needing to copy the memory to a new object?  For example, let's say I want to calculate the outer product of a column within a `matrix` and a `vector` object.  Right now, the way I do this is like so:

```c++
#define VIENNACL_WITH_OPENCL 1

#include "viennacl/matrix.hpp"
#include "viennacl/vector.hpp"
#include "viennacl/linalg/prod.hpp"

int main(){
    
  // initialize objects
  viennacl::matrix<float> vcl_A = viennacl::scalar_matrix<float>(10, 1, (float)(2));
  viennacl::vector<float> vcl_B = viennacl::scalar_vector<float>(5, (float)(3));

  // pull column
  viennacl::vector<float> C = viennacl::column(vcl_A, 0); 

  // calculate outer prod
  viennacl::matrix<float> D = viennacl::linalg::outer_prod(C, vcl_B);

}
```

This however creates a copy of the column within `vcl_A`.  Is there a way to pass it to `outer_prod` (or any other function) that wouldn't create a copy?  My first thought was to try and pass the `viennacl::column` call to the function but it results in a compiler error.

**Comment by karlrupp** [comment]
You can create a `vector_base` object with the correct layout and pass that to `outer_prod`. Try the following:

    viennacl::vector_base<float> C(vcl_A.handle(), vcl_A.size1(), 0, vcl_A.internal_size2());

**Comment by cdeterman** [comment]
@karlrupp thanks, that seems to do it. Thank you very much.
