### ISSUE TITLE
Extracting Lower Diagonal of LU Decomposition

### ISSUE THREAD

**Issue by Stevo15025** [viennacl/viennacl-dev#230]
I apologize for the novice question.

In the [documentation](http://viennacl.sourceforge.net/doc/namespaceviennacl_1_1linalg.html#a1050039fb153ae8ad818390a30f96bc4) it says that `lu_factorize` performs "LU factorization of a row-major dense matrix." (or column-major). When I do something like 

```
viennacl::linalg::lu_factorize(vcl_A);
```

Is there a way for me to extract the lower diagonal L?

**Comment by cdeterman** [comment]
@karlrupp I want to revisit this closed issue.  I am completely blanking on how you extract the L/U components following the `lu_factorize` call.

**Comment by karlrupp** [comment]
@cdeterman `lu_factorize` overwrites the input matrix with the factors L and U (i.e. the lower triangular part contains L, the upper diagonal part including the diagonal contains U. The diagonal of L is implicitly given by 1s and not stored). If you need the diagonal of U, you can directly call `diag()` on the resulting matrix.
