### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by robinchrist** [viennacl/viennacl-dev#251]
Hi,
It seems like the CI is broken.

> sudo apt-get install -qq libboost-chrono1.48-dev libboost-date-time1.48-dev libboost-test1.48-dev libboost-system1.48-dev libboost-filesystem1.48-dev libboost-timer1.48-dev libboost-program-options1.48-dev libboost-thread1.48-dev python-yaml lcov
> E: Package 'libboost-chrono1.48-dev' has no installation candidate
> E: Package 'libboost-date-time1.48-dev' has no installation candidate
> E: Package 'libboost-test1.48-dev' has no installation candidate
> E: Package 'libboost-system1.48-dev' has no installation candidate
> E: Package 'libboost-filesystem1.48-dev' has no installation candidate
> E: Package 'libboost-timer1.48-dev' has no installation candidate
> E: Package 'libboost-program-options1.48-dev' has no installation candidate
> E: Package 'libboost-thread1.48-dev' has no installation candidate

**Comment by karlrupp** [comment]
Thanks! This commit fixes the issue:
https://github.com/viennacl/viennacl-dev/commit/c7accc1f3304f9daf38d1cc03454ce335cc8e08d
