### ISSUE TITLE
Custom CUDA kernels?

### ISSUE THREAD

**Issue by cdeterman** [viennacl/viennacl-dev#254]
I am familiar with the means to implement custom OpenCL kernels from the [documentation](http://viennacl.sourceforge.net/doc/manual-custom-kernels.html).  What about custom CUDA kernels?  I know it's not quite as simple but perhaps there is either plans or thoughts on how to accomplish this?

**Comment by karlrupp** [comment]
Here is an example of how to use custom CUDA kernels:
https://github.com/viennacl/viennacl-dev/blob/master/examples/tutorial/custom-cuda.cu

**Comment by cdeterman** [comment]
Thanks, as I am thinking about these kernels am I correct that the padding in OpenCL is also applicable to the CUDA memory backend?

**Comment by karlrupp** [comment]
yes, padding is needed for the CUDA backend as well.
