### ISSUE TITLE
I have a problem with spai 

### ISSUE THREAD

**Issue by RENJIEYM** [viennacl/viennacl-dev#278]
hello,
when i add the header file like "#include "viennacl/linalg/spai.hpp" ", these errors will happen,and i don't know how fix it

/usr/local/cuda-9.0/bin/..//include/viennacl/linalg/detail/spai/qr.hpp(435): error: class "viennacl::context" has no member "opencl_context"

/usr/local/cuda-9.0/bin/..//include/viennacl/linalg/detail/spai/spai-dynamic.hpp(369): error: class "viennacl::context" has no member "opencl_context"

/usr/local/cuda-9.0/bin/..//include/viennacl/linalg/detail/spai/spai-dynamic.hpp(451): error: class "viennacl::context" has no member "opencl_context"

/usr/local/cuda-9.0/bin/..//include/viennacl/linalg/detail/spai/spai-dynamic.hpp(543): error: class "viennacl::context" has no member "opencl_context"

/usr/local/cuda-9.0/bin/..//include/viennacl/linalg/detail/spai/spai.hpp(309): error: class "viennacl::context" has no member "opencl_context"

/usr/local/cuda-9.0/bin/..//include/viennacl/linalg/detail/spai/spai.hpp(539): error: class "viennacl::context" has no member "opencl_context"

/usr/local/cuda-9.0/bin/..//include/viennacl/linalg/spai.hpp(141): error: namespace "viennacl::traits" has no member "opencl_handle"

environment :ubuntu, cuda 9.0, opencl 1.2

**Comment by karlrupp** [comment]
SPAI is only available with OpenCL. You have to enable the OpenCL backend via `VIENNACL_HAVE_OPENCL`.

**Comment by RENJIEYM** [comment]
Thank you for replying so fast，
according to your suggestion, my program has been compiled，and I compile with nvcc, -lOpenCL is also needed.
Thank you again for your help!!!
